<?php

namespace DoctrineORMModule\Proxy\__CG__\Tcmed\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Logradouro extends \Tcmed\Entity\Logradouro implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Tcmed\\Entity\\Logradouro' . "\0" . 'idLogradouro', '' . "\0" . 'Tcmed\\Entity\\Logradouro' . "\0" . 'nomeLogradouro', '' . "\0" . 'Tcmed\\Entity\\Logradouro' . "\0" . 'status', '' . "\0" . 'Tcmed\\Entity\\Logradouro' . "\0" . 'cep', '' . "\0" . 'Tcmed\\Entity\\Logradouro' . "\0" . 'bairroBairro', '' . "\0" . 'Tcmed\\Entity\\Logradouro' . "\0" . 'tipologradouroTipologradouro');
        }

        return array('__isInitialized__', '' . "\0" . 'Tcmed\\Entity\\Logradouro' . "\0" . 'idLogradouro', '' . "\0" . 'Tcmed\\Entity\\Logradouro' . "\0" . 'nomeLogradouro', '' . "\0" . 'Tcmed\\Entity\\Logradouro' . "\0" . 'status', '' . "\0" . 'Tcmed\\Entity\\Logradouro' . "\0" . 'cep', '' . "\0" . 'Tcmed\\Entity\\Logradouro' . "\0" . 'bairroBairro', '' . "\0" . 'Tcmed\\Entity\\Logradouro' . "\0" . 'tipologradouroTipologradouro');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Logradouro $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdLogradouro()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdLogradouro();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdLogradouro', array());

        return parent::getIdLogradouro();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomeLogradouro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomeLogradouro', array());

        return parent::getNomeLogradouro();
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getCep()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCep', array());

        return parent::getCep();
    }

    /**
     * {@inheritDoc}
     */
    public function getBairroBairro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBairroBairro', array());

        return parent::getBairroBairro();
    }

    /**
     * {@inheritDoc}
     */
    public function getTipologradouroTipologradouro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipologradouroTipologradouro', array());

        return parent::getTipologradouroTipologradouro();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdLogradouro($idLogradouro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdLogradouro', array($idLogradouro));

        return parent::setIdLogradouro($idLogradouro);
    }

    /**
     * {@inheritDoc}
     */
    public function setNomeLogradouro($nomeLogradouro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomeLogradouro', array($nomeLogradouro));

        return parent::setNomeLogradouro($nomeLogradouro);
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function setCep($cep)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCep', array($cep));

        return parent::setCep($cep);
    }

    /**
     * {@inheritDoc}
     */
    public function setBairroBairro(\Tcmed\Entity\Bairro $bairroBairro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBairroBairro', array($bairroBairro));

        return parent::setBairroBairro($bairroBairro);
    }

    /**
     * {@inheritDoc}
     */
    public function setTipologradouroTipologradouro(\Tcmed\Entity\TipoLogradouro $tipologradouroTipologradouro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipologradouroTipologradouro', array($tipologradouroTipologradouro));

        return parent::setTipologradouroTipologradouro($tipologradouroTipologradouro);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

    /**
     * {@inheritDoc}
     */
    public function floatToStr($get, $dec = 2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'floatToStr', array($get, $dec));

        return parent::floatToStr($get, $dec);
    }

    /**
     * {@inheritDoc}
     */
    public function strToFloat($check)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'strToFloat', array($check));

        return parent::strToFloat($check);
    }

    /**
     * {@inheritDoc}
     */
    public function strToDate($strDateTime = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'strToDate', array($strDateTime));

        return parent::strToDate($strDateTime);
    }

    /**
     * {@inheritDoc}
     */
    public function dateToStr($date, $full = false, $obj = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'dateToStr', array($date, $full, $obj));

        return parent::dateToStr($date, $full, $obj);
    }

}
