<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Teste extends \Application\Entity\Teste implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Teste' . "\0" . 'idTeste', '' . "\0" . 'Application\\Entity\\Teste' . "\0" . 'campo1', '' . "\0" . 'Application\\Entity\\Teste' . "\0" . 'campo2', '' . "\0" . 'Application\\Entity\\Teste' . "\0" . 'campo3');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Teste' . "\0" . 'idTeste', '' . "\0" . 'Application\\Entity\\Teste' . "\0" . 'campo1', '' . "\0" . 'Application\\Entity\\Teste' . "\0" . 'campo2', '' . "\0" . 'Application\\Entity\\Teste' . "\0" . 'campo3');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Teste $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdTeste()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdTeste();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdTeste', array());

        return parent::getIdTeste();
    }

    /**
     * {@inheritDoc}
     */
    public function getCampo1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCampo1', array());

        return parent::getCampo1();
    }

    /**
     * {@inheritDoc}
     */
    public function getCampo2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCampo2', array());

        return parent::getCampo2();
    }

    /**
     * {@inheritDoc}
     */
    public function getCampo3()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCampo3', array());

        return parent::getCampo3();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdTeste($idTeste)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdTeste', array($idTeste));

        return parent::setIdTeste($idTeste);
    }

    /**
     * {@inheritDoc}
     */
    public function setCampo1($campo1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCampo1', array($campo1));

        return parent::setCampo1($campo1);
    }

    /**
     * {@inheritDoc}
     */
    public function setCampo2($campo2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCampo2', array($campo2));

        return parent::setCampo2($campo2);
    }

    /**
     * {@inheritDoc}
     */
    public function setCampo3($campo3)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCampo3', array($campo3));

        return parent::setCampo3($campo3);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

    /**
     * {@inheritDoc}
     */
    public function floatToStr($get, $dec = 2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'floatToStr', array($get, $dec));

        return parent::floatToStr($get, $dec);
    }

    /**
     * {@inheritDoc}
     */
    public function strToFloat($check)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'strToFloat', array($check));

        return parent::strToFloat($check);
    }

    /**
     * {@inheritDoc}
     */
    public function strToDate($strDateTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'strToDate', array($strDateTime));

        return parent::strToDate($strDateTime);
    }

    /**
     * {@inheritDoc}
     */
    public function dateToStr($date, $full = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'dateToStr', array($date, $full));

        return parent::dateToStr($date, $full);
    }

}
