<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Contato extends \Application\Entity\Contato implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Contato' . "\0" . 'idContato', '' . "\0" . 'Application\\Entity\\Contato' . "\0" . 'userUser', '' . "\0" . 'Application\\Entity\\Contato' . "\0" . 'contatoUser', '' . "\0" . 'Application\\Entity\\Contato' . "\0" . 'grupoGrupo');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Contato' . "\0" . 'idContato', '' . "\0" . 'Application\\Entity\\Contato' . "\0" . 'userUser', '' . "\0" . 'Application\\Entity\\Contato' . "\0" . 'contatoUser', '' . "\0" . 'Application\\Entity\\Contato' . "\0" . 'grupoGrupo');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Contato $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($idContato)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($idContato));

        return parent::setId($idContato);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdContato()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdContato();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdContato', array());

        return parent::getIdContato();
    }

    /**
     * {@inheritDoc}
     */
    public function getUserUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserUser', array());

        return parent::getUserUser();
    }

    /**
     * {@inheritDoc}
     */
    public function getContatoUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContatoUser', array());

        return parent::getContatoUser();
    }

    /**
     * {@inheritDoc}
     */
    public function getGrupoGrupo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGrupoGrupo', array());

        return parent::getGrupoGrupo();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdContato($idContato)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdContato', array($idContato));

        return parent::setIdContato($idContato);
    }

    /**
     * {@inheritDoc}
     */
    public function setUserUser($userUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserUser', array($userUser));

        return parent::setUserUser($userUser);
    }

    /**
     * {@inheritDoc}
     */
    public function setContatoUser(\Application\Entity\User $contatoUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContatoUser', array($contatoUser));

        return parent::setContatoUser($contatoUser);
    }

    /**
     * {@inheritDoc}
     */
    public function setGrupoGrupo($grupoGrupo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGrupoGrupo', array($grupoGrupo));

        return parent::setGrupoGrupo($grupoGrupo);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

    /**
     * {@inheritDoc}
     */
    public function floatToStr($get, $dec = 2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'floatToStr', array($get, $dec));

        return parent::floatToStr($get, $dec);
    }

    /**
     * {@inheritDoc}
     */
    public function strToFloat($check)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'strToFloat', array($check));

        return parent::strToFloat($check);
    }

    /**
     * {@inheritDoc}
     */
    public function strToDate($strDateTime = '')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'strToDate', array($strDateTime));

        return parent::strToDate($strDateTime);
    }

    /**
     * {@inheritDoc}
     */
    public function dateToStr($date, $full = false, $obj = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'dateToStr', array($date, $full, $obj));

        return parent::dateToStr($date, $full, $obj);
    }

}
