<?php

namespace DoctrineORMModule\Proxy\__CG__\Application\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Usuario extends \Application\Entity\Usuario implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Usuario' . "\0" . 'idUsuario', '' . "\0" . 'Application\\Entity\\Usuario' . "\0" . 'nomeUsuario', '' . "\0" . 'Application\\Entity\\Usuario' . "\0" . 'nickname', '' . "\0" . 'Application\\Entity\\Usuario' . "\0" . 'senhaUsuario', '' . "\0" . 'Application\\Entity\\Usuario' . "\0" . 'emailUsuario', '' . "\0" . 'Application\\Entity\\Usuario' . "\0" . 'salt', '' . "\0" . 'Application\\Entity\\Usuario' . "\0" . 'createdAt', '' . "\0" . 'Application\\Entity\\Usuario' . "\0" . 'updatedAt', '' . "\0" . 'Application\\Entity\\Usuario' . "\0" . 'situacao', '' . "\0" . 'Application\\Entity\\Usuario' . "\0" . 'isAdmin', '' . "\0" . 'Application\\Entity\\Usuario' . "\0" . 'lembreteSenha', '' . "\0" . 'Application\\Entity\\Usuario' . "\0" . 'activationKey', '' . "\0" . 'Application\\Entity\\Usuario' . "\0" . 'active', '' . "\0" . 'Application\\Entity\\Usuario' . "\0" . 'tipo', '' . "\0" . 'Application\\Entity\\Usuario' . "\0" . 'role');
        }

        return array('__isInitialized__', '' . "\0" . 'Application\\Entity\\Usuario' . "\0" . 'idUsuario', '' . "\0" . 'Application\\Entity\\Usuario' . "\0" . 'nomeUsuario', '' . "\0" . 'Application\\Entity\\Usuario' . "\0" . 'nickname', '' . "\0" . 'Application\\Entity\\Usuario' . "\0" . 'senhaUsuario', '' . "\0" . 'Application\\Entity\\Usuario' . "\0" . 'emailUsuario', '' . "\0" . 'Application\\Entity\\Usuario' . "\0" . 'salt', '' . "\0" . 'Application\\Entity\\Usuario' . "\0" . 'createdAt', '' . "\0" . 'Application\\Entity\\Usuario' . "\0" . 'updatedAt', '' . "\0" . 'Application\\Entity\\Usuario' . "\0" . 'situacao', '' . "\0" . 'Application\\Entity\\Usuario' . "\0" . 'isAdmin', '' . "\0" . 'Application\\Entity\\Usuario' . "\0" . 'lembreteSenha', '' . "\0" . 'Application\\Entity\\Usuario' . "\0" . 'activationKey', '' . "\0" . 'Application\\Entity\\Usuario' . "\0" . 'active', '' . "\0" . 'Application\\Entity\\Usuario' . "\0" . 'tipo', '' . "\0" . 'Application\\Entity\\Usuario' . "\0" . 'role');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Usuario $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUsuario()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdUsuario();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUsuario', array());

        return parent::getIdUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function getNomeUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomeUsuario', array());

        return parent::getNomeUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function getNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', array());

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function getNickname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNickname', array());

        return parent::getNickname();
    }

    /**
     * {@inheritDoc}
     */
    public function getSenhaUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSenhaUsuario', array());

        return parent::getSenhaUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailUsuario', array());

        return parent::getEmailUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', array());

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', array());

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', array());

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getSituacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSituacao', array());

        return parent::getSituacao();
    }

    /**
     * {@inheritDoc}
     */
    public function getIsAdmin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIsAdmin', array());

        return parent::getIsAdmin();
    }

    /**
     * {@inheritDoc}
     */
    public function getLembreteSenha()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLembreteSenha', array());

        return parent::getLembreteSenha();
    }

    /**
     * {@inheritDoc}
     */
    public function getRole($obj = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRole', array($obj));

        return parent::getRole($obj);
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUsuario($idUsuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUsuario', array($idUsuario));

        return parent::setIdUsuario($idUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function setNomeUsuario($nomeUsuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomeUsuario', array($nomeUsuario));

        return parent::setNomeUsuario($nomeUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function setNickname($nickname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNickname', array($nickname));

        return parent::setNickname($nickname);
    }

    /**
     * {@inheritDoc}
     */
    public function setSenhaUsuario($senhaUsuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSenhaUsuario', array($senhaUsuario));

        return parent::setSenhaUsuario($senhaUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function encryptPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'encryptPassword', array($password));

        return parent::encryptPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailUsuario($emailUsuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailUsuario', array($emailUsuario));

        return parent::setEmailUsuario($emailUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function setSalt($salt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSalt', array($salt));

        return parent::setSalt($salt);
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', array());

        return parent::setCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', array());

        return parent::setUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setSituacao($situacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSituacao', array($situacao));

        return parent::setSituacao($situacao);
    }

    /**
     * {@inheritDoc}
     */
    public function setIsAdmin($isAdmin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsAdmin', array($isAdmin));

        return parent::setIsAdmin($isAdmin);
    }

    /**
     * {@inheritDoc}
     */
    public function setLembreteSenha($lembreteSenha)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLembreteSenha', array($lembreteSenha));

        return parent::setLembreteSenha($lembreteSenha);
    }

    /**
     * {@inheritDoc}
     */
    public function getActivationKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivationKey', array());

        return parent::getActivationKey();
    }

    /**
     * {@inheritDoc}
     */
    public function setActivationKey($activationKey)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActivationKey', array($activationKey));

        return parent::setActivationKey($activationKey);
    }

    /**
     * {@inheritDoc}
     */
    public function getActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActive', array());

        return parent::getActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setActive($active)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', array($active));

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipo', array());

        return parent::getTipo();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipo($tipo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipo', array($tipo));

        return parent::setTipo($tipo);
    }

    /**
     * {@inheritDoc}
     */
    public function setRole(\Application\Entity\AppRole $role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRole', array($role));

        return parent::setRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array());

        return parent::toArray();
    }

    /**
     * {@inheritDoc}
     */
    public function floatToStr($get, $dec = 2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'floatToStr', array($get, $dec));

        return parent::floatToStr($get, $dec);
    }

    /**
     * {@inheritDoc}
     */
    public function strToFloat($check)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'strToFloat', array($check));

        return parent::strToFloat($check);
    }

    /**
     * {@inheritDoc}
     */
    public function strToDate($strDateTime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'strToDate', array($strDateTime));

        return parent::strToDate($strDateTime);
    }

    /**
     * {@inheritDoc}
     */
    public function dateToStr($date, $full = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'dateToStr', array($date, $full));

        return parent::dateToStr($date, $full);
    }

}
