<h3><?php echo $this->data['titulo']; ?></h3>
<br />
<?php
/* @var $fh \Application\View\Helper\FormHelp */
if(isset($this->data['ajax']) AND $this->data['ajax'] === FALSE){
    $fh = $this->formHelp($this,$this->form,$this->url('app/default',array('controller'=>'users','action'=>$this->data['action']),[],FALSE,FALSE));
}else{
    $fh = $this->formHelp($this,$this->form,$this->url('app/default',array('controller'=>'users','action'=>$this->data['action'])));
}
$fh->setHorizontal(true);
$fh->formInit('Cadastro Usuario');
    $fh->openCol('6')->text('nome_usuario')->closeCol();
    $fh->openCol('6')->text('nickname')->closeCol();
$fh->lineDown();
    $fh->openCol('6')->text('email_usuario')->closeCol();
    $fh->openCol('6')->select('situacao')->closeCol();
$fh->lineDown();
    $fh->openCol('6')->text('lembreteSenha')->closeCol();
    $fh->openCol('6')->select('tipo')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->password('senha_usuario')->closeCol();
$fh->lineDown();                                      
    $fh->openCol('12')->password('confirmation')->closeCol();
$fh->lineDown();                                      
    $fh->openCol('12')->Submit('submit')->closeCol();
$fh->closeLine()->formEnd();

?>

<script lang="javascritp">   
    
    function isValid(){
        return true;
    }
    
</script>