<h3><?php echo $this->dataView['titulo']; ?></h3>
<br />
<?php
/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp($this,$this->form,$this->url('app/default',array('controller'=>'users','action'=>$this->dataView['action']),[],FALSE,$this->dataView['ajax']));
$fh->setHorizontal(true);
$fh->formInit('Cadastro User');
    $fh->openCol('12')->text('nome')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->text('usuarioId')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->text('statusMsg')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->select('status')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->select('statusChat')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->Submit('submit')->closeCol();
$fh->closeLine()->formEnd();
?>

<div class="input-daterange">
    <input type="text" class="input-small" value="2012-04-05" />
    <span class="add-on">to</span>
    <input type="text" class="input-small" value="2012-04-19" />
</div>

<script lang="javascritp">   
    
    function isValid(){
        return true;
    }
    
</script>
