<?php
/* @var $table \Application\View\Helper\Table */
$table = $this->table();
$controller = 'administradoras';
$route = 'tcmed/default';
?>
<h1>Administradoras</h1>
<br />
<p>
    <button class="btn btn-primary" onclick="<?php echo $this->url($route, array('controller' => $controller, 'action' => 'new')); ?>">Novo</button>
</p>
<?php
$table->openTable(TRUE);
$table->renderThead(['ID', 'Razao Social', 'Nome Fantasia', 'CNPJ', 'status', 'Endereco', 'Contato','Hold', 'Hold Virtual', 'Referencia Tcmed','Ação']);
/* @var $entity \Tcmed\Entity\Administradora */
foreach ($this->data as $entity) {
    $table->renderLine([
        $entity->getId(),
        $entity->getRazaoSocial(),
        $entity->getFantasiaAdministradora(),
        $entity->getCnpj(),
        $entity->getStatus(),
        $entity->getEndereco()->getId(),
        $entity->getContato()->getId(),
        $entity->getHold()->getId(),
        $entity->getHold()->getId(),
        $entity->getReferencia(),
        $entity->getId(),
    ]);
}
$table->renderCloseTable();
?>
<br />

<center>
    <?php echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator'); ?>    
</center>

<script lang="javascript">
    function edit(key) {
        var data = {url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'edit'), [], FALSE, FALSE); ?>" + "/" + key};
        processa(data);
    }
    function del(key) {
        var msg = "Deseja mesmo excluir este registro?";
        if (!confirm(msg)) {
            return;
        }
        var data = {url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'delete'), [], FALSE, FALSE); ?>" + "/" + key};
        processa(data);
    }
</script>