
<div class="container">
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <div class="login-panel panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Entrar</h3>
                </div>
                <?php if($this->error): ?>
                <p>Usuário ou senha inválidos</p>
                <?php endif; ?>
                <div class="panel-body">
<?php
$form = $this->form;
$form->setAttribute('action',$this->url('application-auth',[],[],FALSE,FALSE));
$form->prepare();
?>

                    <?php echo $this->form()->openTag($form); ?>
                        <fieldset>                           
                            <?php echo $this->formCollection($form); ?>
<!-- 
                            <div class="form-group">
                                <input class="form-control" placeholder="E-mail" name="email" type="email" autofocus>
                            </div>
                            <div class="form-group">
                                <input class="form-control" placeholder="Password" name="password" type="password" value="">
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input name="remember" type="checkbox" value="lembrar">Lembrar
                                </label>
                            </div>
                            <input type="submit" class='btn btn-lg btn-success btn-block'>
-->                            
                        </fieldset>
                    <?php echo $this->form()->closeTag($form); ?>
                </div>
            </div>
        </div>
    </div>
</div>
<script lang="javascritp">   
    
    
    function isValid(){
        return true;
    }
    
</script>