
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="login-panel panel panel-success">
                <div class="panel-heading">
                    <h3 class="panel-title">Entrar</h3>
                </div>
                <?php if($this->error): ?>
                <h2>Usuário ou senha inválidos</h2>
                <?php endif; ?>
                <div class="panel-body">
                <?php
                /* @var $fh \Application\View\Helper\FormHelp */                
                $fh = $this->formHelp($this,$this->form,$this->url('application-auth',[],[],FALSE,$this->dataView['ajax']));

                $fh->setHorizontal(true);
                $fh->formInit('Tecnomed - Login do Sistema');
                    $fh->openCol('12')->text('email')->closeCol();
                $fh->lineDown();
                    $fh->openCol('12')->password('password')->closeCol();
                $fh->lineDown(); 
                    $fh->openCol('12')->checkbox('remember')->closeCol();
                $fh->lineDown();                                      
                    $fh->openCol('12')->Submit('submit')->closeCol();
                $fh->closeLine()->formEnd();
                
                ?>

                </div>
            </div>
        </div>
    </div>
</div>
<script lang="javascript">   
    
    
    function isValid(){
        return true;
    }
    
</script>