<?php
/* @var $table \Application\View\Helper\Table
 * @author Allan Davini */
$table = $this->table();
$controller = 'epifuncoes';
$route = 'tcmed/default';
?>
<h1>Epi Funcoes</h1>
<br />
<p>
    <button class="btn btn-primary" onclick="<?php echo $this->url($route, array('controller' => $controller, 'action' => 'new')); ?>">Novo</button>
</p>
<?php
$table->openTable(TRUE);
$table->renderThead(['ID', 'eficaz', 'idEpi', 'idFuncao', 'idRisco', 'Ação']);
/* @var $entity \Tcmed\Entity\EpiFuncao */
foreach ($this->data as $entity) {
    $table->renderLine([
        $entity->getId(),
        $entity->getEficaz(),
        $entity->getIdEpi()->getEpi(),
        $entity->getIdFuncao()->getIFuncao(),
        $entity->getIdRisco()->getRisco(),
        $entity->getId(),
    ]);
}
$table->renderCloseTable();
?>
<br />

<center>
    <?php echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator'); ?>    
</center>

<script lang="javascript">
    function edit(key) {
        var data = {url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'edit'), [], FALSE, FALSE); ?>" + "/" + key};
        processa(data);
    }
    function del(key) {
        var msg = "Deseja mesmo excluir este registro?";
        if (!confirm(msg)) {
            return;
        }
        var data = {url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'delete'), [], FALSE, FALSE); ?>" + "/" + key};
        processa(data);
    }
</script>