<h3><?php echo $this->dataView['titulo']; 
$controller = 'funcao';
$route = 'tcmed/default';
?></h3>
<br />
<?php
/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp($this,$this->form,$this->url($route,array('controller'=>$controller,'action'=>$this->dataView['action']),[],FALSE,$this->dataView['ajax']));
$fh->setHorizontal(true);
$fh->formInit('Cadastro Funcao:');
    $fh->openCol('12')->text('nomeFuncao')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->text('status')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->text('referencia')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->text('codFuncao')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->select('descricaoDescricao')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->Submit('submit')->closeCol();
$fh->closeLine()->formEnd();
?>

<script lang="javascritp">   
    
    function isValid(){
        return true;
    }
    
</script>
