<?php

foreach ($this->mensagens as $mensagem) {

    /* @var $mensagem \Application\Entity\Enviado */
    $array = [
        "dtime" => $mensagem->getDateEnviado(),
        "typeusr" => "user",
        "msg" => $mensagem->getMensagemMensagem()->getTexto(),
        "userto" => $mensagem->getToUser()->getId(),
        "userby" => $mensagem->getFromUser()->getId()
    ];
}

echo json_encode($array);
