<?php

$array = [];

/* @var $contato \Application\Entity\Contato */
/* @var $contatoGrupo \Application\Entity\Contato */
foreach ($this->data as $key => $contato) { 
    if(is_array($contato)){
        continue;
    }
    if(!$contato->getGrupoGrupo() instanceof \Application\Entity\Grupo){
        $array['us'. $contato->getContatoUser()->getId()] = [
            "name" => $contato->getContatoUser()->getNome(),
            "type" => "user",
            "status" => $contato->getContatoUser()->getStatusChat()
        ];
        continue;
    }
    $array['gr'. $contato->getGrupoGrupo()->getId()] = [
        "name" => $contato->getGrupoGrupo()->getNome(),
        "type" => "group",
        "status" => $contato->getGrupoGrupo()->getStatusChat(),
    ];
    $arrayGrupo = [];
    foreach ($this->data['us' . $contato->getContatoUser()->getId()] as $contatoGrupo){
        $arrayGrupo[$contatoGrupo->getId()] = [
            "name" => $contatoGrupo->getContatoUser()->getNome(),
            "type" => "user",
            "status" => $contatoGrupo->getContatoUser()->getStatusChat()            
        ];
    }
    $array[$contato->getId()]['contatosDoGrupo'] = $arrayGrupo;
}

echo json_encode($array);