<style>
.pagination ul>li{display:inline}
.pagination ul>li>a,.pagination ul>li>span{float:left;padding:0 14px;line-height:38px;text-decoration:none;background-color:#fff;border:1px solid #ddd;border-left-width:0}
.pagination ul>li>a:hover,.pagination ul>.active>a,.pagination ul>.active>span{background-color:#f5f5f5}
.pagination ul>.active>a,.pagination ul>.active>span{color:#999;cursor:default}
.pagination ul>.disabled>span,.pagination ul>.disabled>a,.pagination ul>.disabled>a:hover{color:#999;cursor:default;background-color:transparent}
.pagination ul>li:first-child>a,.pagination ul>li:first-child>span{border-left-width:1px;-webkit-border-radius:3px 0 0 3px;-moz-border-radius:3px 0 0 3px;border-radius:3px 0 0 3px}
.pagination ul>li:last-child>a,.pagination ul>li:last-child>span{-webkit-border-radius:0 3px 3px 0;-moz-border-radius:0 3px 3px 0;border-radius:0 3px 3px 0}
.pagination-centered{text-align:center}
.pagination-right{text-align:right}
</style>
<?php
$urlPattern = $_SERVER['REQUEST_URI'];
$urls = explode("?", $urlPattern);
$urlPattern = $urls[0];

$formatUrl = function ($page) use ($urlPattern) {
    if (!preg_match('/page/', $urlPattern)) {
        return "javascript:processa({url:'" . $urlPattern . '/page/' . (int) $page . "'});";
    } else {
        return "javascript:processa({url:'" . preg_replace('@/page/\d@', '/page/' . (int) $page, $urlPattern) . "'});";
    }
};

if ($this->pageCount):
    ?>
    <div class="pagination pagination-centered">
        <ul>
            <?php if (isset($this->previous)): ?>
                <li><a href="<?php echo $formatUrl($this->previous); ?>">«</a></li>
            <?php else: ?>
                <li class="disabled"><a href="javascript:processa({url:''});">«</a></li>
            <?php endif; ?>
            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li>
                        <a href="<?php echo $formatUrl($page); ?>"><?php echo $page; ?></a>
                    </li> 
                <?php else: ?>
                    <li class="active">
                        <a href="javascript:processa({url:''});"><?php echo $page; ?></a>
                    </li>      
                <?php endif; ?>
            <?php endforeach; ?>
            <?php if (isset($this->next)): ?>
                <li><a href="<?php echo $formatUrl($this->next); ?>">»</a></li>
            <?php else: ?>
                <li class="disabled"><a href="javascript:processa({url:''});">»</a></li>
            <?php endif; ?>
        </ul>
    </div>
<?php endif; ?>