<?php
/* @var $table \Application\View\Helper\Table */
$table = $this->table();
$controller = 'grupos';
?>
<h1>Grupos</h1>
<br />

    <?php
    $fh = $this->formHelp($this, $this->form);
    $url = $this->url('app/default',array('controller'=>$controller,'action'=>'new'));
    $fh->openCol('1')->button(["onclick"=>$url], "Novo")->closeCol();
    $fh->openCol('3')->text('nome', [
        "spanLabel" => true,
        "clean" => false,
        "extra" => [
            "type" => "button",
            "icon" => "user"
        ]
    ])->closeCol();
    ?>
<br>
<br>
<div class="col-md-12">
    
    <?php
    $table->openTable(TRUE); 
    $table->renderThead(['ID','Nome','Mensagem Status','Chat Status','Status','Ação'])  ;     
    foreach($this->data as $entity){
        $table->renderLine([
            $entity->getId(),
            $entity->getNome(),
            $entity->getStatusMsg(),
            $entity->getStatusChat(),
            $entity->getStatus(),
            $entity->getId(),
        ]);
    } 
    $table->renderCloseTable();
    ?>
</div>
<br />

<center>
    <?php echo $this->paginationControl($this->data,'Sliding','partials/paginator'); ?>    
</center>

<script lang="javascript">      
    function edit(key){
        var data = {url : "<?php echo $this->url('app/default',array('controller'=>$controller,'action'=>'edit'),[],FALSE,FALSE);?>" + "/" + key };
        processa(data);
    }
    function del(key){
        var msg = "Deseja mesmo excluir este registro?";
        if(!confirm(msg)){
            return;
        }
        var data = {url : "<?php echo $this->url('app/default',array('controller'=>$controller,'action'=>'delete'),[],FALSE,FALSE);?>" + "/" + key };
        processa(data);
    }    
</script>