<?php
/* @var $table \Application\View\Helper\Table */
$table = $this->table();
$controller = 'consultas';
$route = 'tcmed/default';
?>
<h1>Consultas</h1>
<br />
<p>
    <button class="btn btn-primary" onclick="<?php echo $this->url($route, array('controller' => $controller, 'action' => 'new')); ?>">Novo</button>
</p>
<?php
$table->openTable(TRUE);
$table->renderThead(['ID', 'idFuncionario', 'status', 'Questionario', 'cargoCargo', 'clinicaClinica', 'medicoMedico', 'setorSetor', 'Ação']);
/* @var $entity \Tcmed\Entity\Consulta */
foreach ($this->data as $entity) {
    $table->renderLine([
        $entity->getId(),
        $entity->getIdFuncionario(),
        $entity->getStatus(),
        $entity->getQuestionario()->getIdQuestionario(),
        $entity->getCargoCargo()->getNomeCargo(),
        $entity->getClinicaClinica()->getRazaoSocial(),
        $entity->getMedicoMedico()->getNomeMedico(),
        $entity->getSetorSetor()->getNomeSetor(),
        $entity->getId()
    ]);
}
$table->renderCloseTable();
?>
<br />

<center>
    <?php echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator'); ?>    
</center>

<script lang="javascript">
    function edit(key) {
        var data = {url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'edit'), [], FALSE, FALSE); ?>" + "/" + key};
        processa(data);
    }
    function del(key) {
        var msg = "Deseja mesmo excluir este registro?";
        if (!confirm(msg)) {
            return;
        }
        var data = {url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'delete'), [], FALSE, FALSE); ?>" + "/" + key};
        processa(data);
    }
</script>