<?php echo $this->doctype(); ?>
<html lang="pt">

    <head>
        <meta charset="utf-8">

        <?php echo $this->headTitle('AEM Sistemas' . 'Tecnomed')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <!-- MetisMenu CSS -->
        <!-- Custom CSS -->
        <!-- Meu CSS -->
        <!-- Custom Fonts -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath('css/font-awesome/css/font-awesome.min.css'))
                ->prependStylesheet($this->basePath('css/mycss.css'))
                ->prependStylesheet($this->basePath('css/sb-admin-2.css'))
                ->prependStylesheet($this->basePath('css/metisMenu.min.css'))
                ->prependStylesheet($this->basePath('bootstrap/dist/css/bootstrap.min.css'))
                ->prependStylesheet($this->basePath('css/tecnomed.min.css'))
        ?>

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- Scripts -->
        <!-- jQuery -->
        <!-- Meu script -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath('js/myscript.js'))
                ->prependFile($this->basePath('js/playplugin.js'))
                ->prependFile($this->basePath('js/sb-admin-2.js'))
                ->prependFile($this->basePath('js/metisMenu.min.js'))
                ->prependFile($this->basePath('bootstrap/dist/js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery.min.js'))
        ;
        ?>


    </head>
    <body>      
        <div id="wrapper">
            <?php echo $this->content; ?>
        <!-- Page Content -->
        <div id="page-wrapper">
            <div class="container-fluid">
                <div id="inter">

                </div>
                <!-- /.row -->
            </div>
            <!-- /.container-fluid -->
        </div>
        <!-- /#page-wrapper -->   
        </div>
        <!-- /#wrapper -->
    </body>
</html>
