    <?php echo $this->doctype(); ?>
<html lang="pt">

    <head>
        <meta charset="utf-8">

        <?php echo $this->headTitle('AEM Sistemas' . 'Tecnomed')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <!-- MetisMenu CSS -->
        <!-- Custom CSS -->
        <!-- Meu CSS -->
        <!-- Custom Fonts -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath('css/main.css'))
                ->prependStylesheet($this->basePath('css/mycss.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap-datepicker3.standalone.css'))
                ->prependStylesheet($this->basePath('css/pagination.min.css'))
                ->prependStylesheet($this->basePath('css/sb-admin-2.min.css'))
                ->prependStylesheet($this->basePath('css/metisMenu.min.css'))
                ->prependStylesheet($this->basePath('css/font-awesome.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

        <!-- Scripts -->
        <!-- jQuery -->
        <!-- Meu script -->
        <?php
        echo $this->headScript()
                //->prependFile($this->basePath('js/ajaxAutoComp.js'))
                //->prependFile($this->basePath('js/jqueryAutoComp.js'))
                ->prependFile($this->basePath('js/jquery.tablesorter.min.js'))
                ->prependFile($this->basePath('js/jquery.autocomplete.js'))
                ->prependFile($this->basePath('js/ajax.js'))
                ->prependFile($this->basePath('js/jquery.maskMoney.js'))
                ->prependFile($this->basePath('locales/bootstrap-datepicker.pt-BR.min.js'))
                ->prependFile($this->basePath('js/metisMenu.min.js'))
                ->prependFile($this->basePath('js/bootstrap-datepicker.js'))
                ->prependFile($this->basePath('js/myscript.js'))
                ->prependFile($this->basePath('js/Actions.js'))
                ->prependFile($this->basePath('js/Modules.js'))
                ->prependFile($this->basePath('bootstrap/dist/js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/main.min.js'))
        ;
        ?>


    </head>
    <body>  
<script type="text/javascript">
    var auth = false;
    var login = false;
</script>
        <?php if ($this->UserIdentity() != FALSE AND !isset($this->dataView['LOGIN'])): ?>
<script type="text/javascript">
    auth = true;
</script>

            <div id="wrapper">
                <?php echo $this->content; ?>
                <!-- Page Content -->
                <div id="page-wrapper">
                    <div class="container-fluid">
                        <div id="inter">
                        </div>
                        <!-- /.row -->
                    </div>
                    <!-- /.container-fluid -->
                </div>
                <!-- /#page-wrapper -->   
            </div>
            <!-- /#wrapper -->      
        <?php else: ?>
            <?php echo $this->content; ?>
        <?php endif; ?>
<script type="text/javascript">
    /**
     * Scripts de Inicializaçao pos login
     */
    if(auth && !login){
        $(function () {
            action.load();
        });        
    }
</script>
        <?php // echo $this->inlineScript() ?>
    </body>
</html>
