<h3><?php echo $this->dataView['titulo']; ?></h3>
<br />
<?php
/* @var $fh \Application\View\Helper\FormHelp */
$fh = $this->formHelp($this,$this->form,$this->url('app/default',array('controller'=>'usuarios','action'=>$this->data['action']),[],FALSE,$this->dataView['ajax']));
$fh->setHorizontal(true);
$fh->formInit('Cadastro Usuario');
    $fh->openCol('6')->text('nome_usuario')->closeCol();
    $fh->openCol('6')->calend('nickname')->closeCol();
$fh->lineDown();
    $fh->openCol('6')->text('email_usuario')->closeCol();
    $fh->openCol('6')->select('situacao')->closeCol();
$fh->lineDown();
    $fh->openCol('6')->text('lembreteSenha')->closeCol();
    $fh->openCol('6')->select('tipo')->closeCol();
$fh->lineDown();
    $fh->openCol('12')->password('senha_usuario')->closeCol();
$fh->lineDown();                                      
    $fh->openCol('12')->password('confirmation')->closeCol();
$fh->lineDown();                                      
    $fh->openCol('12')->Submit('submit')->closeCol();
$fh->closeLine()->formEnd();

?>

<script lang="javascritp">   
    
    function isValid(){
        return true;
    }
    
</script>