<?php
/* @var $table \Application\View\Helper\Table */
$table = $this->table();
?>
<h1>Users</h1>
<br />
<p>
    <button class="btn btn-primary" onclick="<?php echo $this->url('app/default',array('controller'=>'usuarios','action'=>'new')); ?>">Novo</button>
</p>
<?php

    $table->openTable(TRUE)  ; 
    $table->renderThead([
        'ID',
        'Nome',
        'Login',
        'Email',
        'Status',
        'Lembrete',
        'Tipo',
        'Papel',
        'Activado',
        'Activado key',
        'Ação',
    ]);     
    foreach($this->data as $entity){
        /* @var $entity \Application\Entity\Usuario */
        $data = [];
        $data[]= $entity->getIdUsuario();
        $data[]= $entity->getNomeUsuario();
        $data[]= $entity->getNickname();
        $data[]= $entity->getEmailUsuario();
        $data[]= $entity->getSituacao();
        $data[]= $entity->getLembreteSenha();
        $data[]= $entity->getTipo();
        $data[]= $entity->getRole();
        $data[]= $entity->getActive()? 'ativado' : 'pendente';       
        $data[]= $entity->getActivationKey();       
        $data[]= $entity->getIdUsuario();       
        $table->renderLine($data);
    } 
    $table->renderCloseTable();
?>
<br />

<center>
    <?php echo $this->paginationControl($this->data,'Sliding','partials/paginator'); ?>    
</center>

<script lang="javascript">      
    function edit(key){
        var data = {url : "<?php echo $this->url('app/default',array('controller'=>'usuarios','action'=>'edit'),[],FALSE,FALSE);?>" + "/" + key };
        processa(data);
    }
    function del(key){
        var msg = "Deseja mesmo excluir este registro?";
        if(!confirm(msg)){
            return;
        }
        var data = {url : "<?php echo $this->url('app/default',array('controller'=>'usuarios','action'=>'delete'),[],FALSE,FALSE);?>" + "/" + key };
        processa(data);
    }    
</script>