<?php
/* @var $table \Application\View\Helper\Table
 * @author Allan Davini */
$table = $this->table();
$controller = 'respostas';
$route = 'tcmed/default';
?>
<h1>Respostas</h1>
<br />
<p>
    <button class="btn btn-primary" onclick="<?php echo $this->url($route, array('controller' => $controller, 'action' => 'new')); ?>">Novo</button>
</p>
<?php
$table->openTable(TRUE);
$table->renderThead(['ID', 'Resposta', 'respostaCheck', 'cidadeBairro', 'Pergunta', 'consultaConsulta', 'Ação']);
/* @var $entity \Tcmed\Entity\Resposta */
foreach ($this->data as $entity) {
    $table->renderLine([
        $entity->getId(),
        $entity->getResposta(),
        $entity->getRespostaCheck(),
        $entity->getCidadeBairro()->getNomeCidade(),
        $entity->getPergunta()->getPergunta(),
        $entity->getConsultaConsulta()->getIdConsulta(),
        $entity->getId(),
    ]);
}
$table->renderCloseTable();
?>
<br />

<center>
    <?php echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator'); ?>    
</center>

<script lang="javascript">
    function edit(key) {
        var data = {url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'edit'), [], FALSE, FALSE); ?>" + "/" + key};
        processa(data);
    }
    function del(key) {
        var msg = "Deseja mesmo excluir este registro?";
        if (!confirm(msg)) {
            return;
        }
        var data = {url: "<?php echo $this->url($route, array('controller' => $controller, 'action' => 'delete'), [], FALSE, FALSE); ?>" + "/" + key};
        processa(data);
    }
</script>