<?php
/* @var $table \Application\View\Helper\Table */
/* @var $entity \Application\Entity\Parametros */
$table = $this->table();
?>
<h1>Parametros</h1>
<br />
<p>
    <button class="btn btn-primary" onclick="<?php echo $this->url('app/default',array('controller'=>'parametros','action'=>'new')); ?>">Novo</button>
</p>
<?php

    $table->openTable(TRUE)  ; 
    $table->renderThead(['ID','Chave','Conteudo','Descrição','Status','Ação'])  ;     
    foreach($this->data as $entity){
        $data = [];
        $data[]= $entity->getIdParame();
        $data[]= $entity->getChave();
        $data[]= $entity->getConteudo();
        $data[]= $entity->getDescricao();       
        $data[]= $entity->getStatus();       
        $data[]= $entity->getIdParame();
        $table->renderLine($data);
    } 
    $table->renderCloseTable();
?>
<br />

<center>
    <?php echo $this->paginationControl($this->data,'Sliding','partials/paginator'); ?>    
</center>

<script lang="javascript">      
    function edit(key){
        var data = {url : "<?php echo $this->url('app/default',array('controller'=>'parametros','action'=>'edit'),[],FALSE,FALSE);?>" + "/" + key };
        processa(data);
    }
    function del(key){
        var msg = "Deseja mesmo excluir este registro?";
        if(!confirm(msg)){
            return;
        }
        var data = {url : "<?php echo $this->url('app/default',array('controller'=>'parametros','action'=>'delete'),[],FALSE,FALSE);?>" + "/" + key };
        processa(data);
    }    
</script>