<!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">


        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>

        <a id="logo" class="navbar-brand">
            <img src="/img/logo_tecnomed.png" style="width: 130px; margin-top: -10px">
        </a>

    </div>

    <div class="nav navbar-nav">
        <button id="toggle" class="btn btn-default navbar-btn"><i class="fa fa-bars"></i></button>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <button id="godown" class="btn btn-default navbar-btn"><i class="fa fa-arrow-left"></i></button>
        <button id="goup" class="btn btn-default navbar-btn"><i class="fa fa-arrow-right"></i></button>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <button id="refresh" class="btn btn-default navbar-btn"><i class="fa fa-refresh"></i></button>
        
    </div>
    
    <!-- /.navbar-header -->
    <ul class="nav navbar-top-links navbar-right">
        <li>
            <button id="messenger" class="btn btn-success navbar-btn" data-toggle="tooltip" data-placement="left" title="Tooltip on bottom">
                <i class="fa fa-group">
                </i>
            </button>
        </li>

        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                </li>
                <li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                </li>
                <li class="divider"></li>
                <li><a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                </li>
            </ul>
            <!-- /.dropdown-user -->
        </li>
        <!-- /.dropdown -->
    </ul>
    <!-- /.navbar-top-links -->

    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav">
                <li class="sidebar-search">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="input-group custom-search-form">
                                <input type="text" class="form-control" placeholder="Search...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                            <!-- /input-group -->
                        </div>
                    </div>
                </li>
            </ul>
            <?php
                $u = $this->UserIdentity() ;
                if ($u != FALSE){
                    $container = $this->navigation('Navigation')->getContainer();
                    echo $this->NewMenu($container)->setUlClass('nav" id="side-menu')->escapeLabels(false);                    
                }
            ?>
            <ul>
            <?php
//                if ($this->UserIdentity() != FALSE){
//                    echo '<pre>' , var_dump($u);
//                }
            ?>
            </ul>
         </div>
        <!-- /.sidebar-collapse -->
    </div>
    <!-- /.navbar-static-side -->
</nav>

<script lang="javascript">   
    
    action.setPublic({SESSAO : module.Cookie.get('SESSAO') });
    action.setPublic({LOGIN : module.Cookie.get('LOGIN')});
   
</script>